### ISSUE TITLE
explode_pdf.py reference to LIT function for EmbeddedFile objects

### ISSUE THREAD

**Issue by cdiraimondi** [jshlbrd/laikaboss-modules#1]
I'm attempting to implement the EXPLODE_PDF module that you developed. I'm noticing that when it attempts to execute I'm receiving the error below for line 47 of the code.

`$ laika.py -o . 7281708618AB25F31121E9714C5130C7.danger
ERROR:root:error on 4817507f-6cb2-4b40-b6ef-a279866ea82b running module EXPLODE_PDF. exception details below:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/laikaboss-2.0-py2.7.egg/laikaboss/si_module.py", line 43, in run
    moduleResult = self._run(scanObject, result, depth, args)
  File "/usr/local/lib/python2.7/dist-packages/laikaboss-2.0-py2.7.egg/laikaboss/modules/explode_pdf.py", line 47, in _run
    if 'Type' in obj.attrs and obj.attrs['Type'] == LIT('EmbeddedFile'):
NameError: global name 'LIT' is not defined
`

I changed line 47 to "if 'Type' in obj.attrs and obj.attrs['Type'] == 'EmbeddedFile':" and that seemed to work.

`$ laika.py -o . 86F8DCA4A1AB530C865F2BA2E3B84C9C.danger
{"source": "CLI", "scan_result": [{"objectHash": "86f8dca4a1ab530c865f2ba2e3b84c9c", "uuid": "ed8e4597-a72a-4317-8c62-f91adcdd12ea", "fileType": ["pdf"], "filename": "86F8DCA4A1AB530C865F2BA2E3B84C9C.danger", "source": "CLI", "origRootUID": "", "uniqID": "", "objectSize": 2194467, "ephID": "", "contentType": [], "parent": "", "parent_order": -1, "scanModules": ["SCAN_YARA", "META_HASH", "EXPLODE_PDF", "META_EXIFTOOL", "DISPOSITIONER", "LOG_FLUENT"], "moduleMetadata": {"DISPOSITIONER": {"Disposition": {"Matches": ["Alert"], "Disposition_File": "/etc/laikaboss/modules/dispositioner/disposition.yara", "Input_Flags": ["yr:suspicious_sig_1", "pdf:nfo:js_embedded"], "Result": "Accept"}}, "META_EXIFTOOL": {"XMP:CreationDate": "2002:01:23 14:25:13Z", "File:FilePermissions": 600, "PDF:HasXFA": "False", "SourceFile": "/dev/shm/laikaboss_tmp/tmpaxzznI", "File:MIMEType": "application/pdf", "File:FileAccessDate": "2016:09:23 08:19:33-07:00", "File:FileModifyDate": "2016:09:23 08:19:33-07:00", "PDF:Keywords": ["DevGuru", "JavaScript", "Quick Reference"], "PDF:CreateDate": "2002:01:23 14:25:13Z", "XMP:MetadataDate": "2002:03:25 12:22:08-05:00", "File:FileSize": 2194467, "XMP:CreateDate": "2002:01:23 14:25:13Z", "XMP:ModDate": "2002:03:25 12:22:08-05:00", "PDF:Title": "DevGuru JavaScript Quick Reference", "PDF:Subject": "JavaScript documentation", "PDF:TaggedPDF": "True", "File:FileType": "PDF", "PDF:PageMode": "UseOutlines", "PDF:Producer": "Acrobat Web Capture 5.0", "XMP:Producer": "Acrobat Web Capture 5.0", "XMP:Keywords": "DevGuru, JavaScript, Quick Reference", "XMP:Author": "The Guru", "File:FileTypeExtension": "PDF", "XMP:Subject": "JavaScript documentation", "PDF:PDFVersion": 1.4, "PDF:ModifyDate": "2002:03:25 12:22:08-05:00", "XMP:Title": "DevGuru JavaScript Introduction ", "File:Directory": "/dev/shm/laikaboss_tmp", "PDF:Author": "The Guru", "PDF:PageCount": 315, "File:FileInodeChangeDate": "2016:09:23 08:19:33-07:00", "XMP:ModifyDate": "2002:01:23 16:57:47-05:00", "File:FileName": "tmpaxzznI", "ExifTool:ExifToolVersion": 10.1, "PDF:Linearized": "False"}, "DISPATCH": {"Rules": ["scan_yara (9)", "meta_hash (9)", "type_is_pdf (9)", "META_EXIFTOOL (9)"], "Conditional Rules": ["send_to_fluent (50)", "DISPOSITION_FILE (10)"]}, "META_HASH": {"HASHES": {"ssdeep": "12288:hSzGKbOY5X9W+XX58gdjD/BaFkjTZoTN+g4yBpUhZ23Wg9dK5FyUzV:jY5XE+Xp86n/4+jFKFZ5Wgwd", "SHA256": "75c6b645b54c7cbd6db76e202e075ebe08d6195f262357202ab7a71f91207eb3", "SHA512": "0092910437102af492310c5f339c0c684796628ea26df3c7d2b33d09413ccfc7a690e74067239bb867d5df0aac95c0df531bcc62504bf3a0e78e328c758b00c1", "SHA1": "5769f59ef07031b6f8539b84dbd14c3f30e1956d", "md5": "86f8dca4a1ab530c865f2ba2e3b84c9c"}}}, "sourceModule": "", "level": 2, "scanTime": 1474643971, "depth": 0, "flags": ["yr:suspicious_sig_1", "pdf:nfo:js_embedded"], "rootUID": "ed8e4597-a72a-4317-8c62-f91adcdd12ea", "order": 0}]}
`

**Comment by zoomequipd** [comment]
+1 on this - is LIT in there by mistake?

**Comment by jshlbrd** [comment]
The issue with LIT isn't that it is included, it's that it isn't imported from pdfminer. Line 20 should be modified to import it. The solution proposed by @cdiraimondi seems simpler, but for the sake of completeness I will update the module to properly import the function.

**Comment by zoomequipd** [comment]
thanks @jshlbrd! here I had lost hope that you'd be responsive.  You've restored my faith!

**Comment by jshlbrd** [comment]
No problem @zoomequipd! I'm happy to help out with issues in this repository, but I should also mention that these modules are seriously out of date and I have no current plans to update them. I'd recommend treating the modules as a jumping off point than a complete solution.
